export const routes: { [index: string]: any } = {
  home: "/",
  login: "/login",
  register: "/register",
  forgot_password: "/forgot_password",
  man: "/man",
  woman: "/woman",
  shoes: "shoes",
  cloth: "cloth",
  shoesMan: "man/shoes",
  clothMan: "man/cloth",
  cart: "/cart",
  baby: "/baby",
  itemDetail: "/item",
};
